### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by fernandoaleman** [smashedtoatoms/asdf-riak#1]
I am unable to install `riak` via `asdf`. Getting an `access denied` on the download URL at AWS S3. Has this been discontinued?

**Comment by smashedtoatoms** [comment]
It would appear that the [troubles at basho](https://www.theregister.co.uk/2017/07/13/will_the_last_person_at_basho_get_the_lights_oh_too_late/) are bubbling up to the users now.  There isn't really anything I can do about this unless someone has a working link to the source.

**Comment by fernandoaleman** [comment]
Oh okay, thank you @smashedtoatoms, I wasn't aware they were practically extinct. Appreciate the quick response. 👍
